---
  fixtures:
    forge_modules:
      easy_type:  enterprisemodules-easy_type
      stdlib:     puppetlabs-stdlib
    repositories:
      facts:        'git://github.com/puppetlabs/puppetlabs-facts.git'
      puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      provision:    
        repo:               git://github.com/enterprisemodules/provision.git
        branch:             docker_run_opts
    symlinks:
      oci_config: "#{source_dir}"
