---
  fixtures:
    forge_modules:
      easy_type:          enterprisemodules-easy_type
      stdlib:             puppetlabs-stdlib
    repositories:
      facts:              https://github.com/puppetlabs/puppetlabs-facts.git
      puppet_agent:       https://github.com/puppetlabs/puppetlabs-puppet_agent.git
      provision:          https://github.com/puppetlabs/provision.git
    symlinks:
      oci_config: "#{source_dir}"
