Gemfile:
  unmanaged: true
# some of the gems in gemfile are in different versions in pdk-template, and module.
# TODO use this section when gem overwrite will be possible
  # required:
  #   'out_of_groups':
  #     - gem: oci
  #       condition: "Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0')"
  #     - gem: activesupport
  #       version: '< 6.0.0'
  #       condition: "Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0')"
  #     - gem: yard
  #       condition: "Gem::Version.new(RUBY_VERSION) > Gem::Version.new('2.3.0')"
  #     - gem: rgen
  #       condition: "Gem::Version.new(RUBY_VERSION) > Gem::Version.new('2.3.0')"
  #     - gem: puppet-strings
  #       condition: "Gem::Version.new(RUBY_VERSION) > Gem::Version.new('2.3.0')"
.gitlab-ci.yml:
  unmanaged: true
.rubocop.yml:
  unmanaged: true
Rakefile:
  unmanaged: true
.rspec:
  required:
    - '--format documentation'
.puppet-lint.rc:
  required:
    - -----fail-on-warnings
    - -----no-140chars-check
    - -----no-quoted_booleans
    - -----no-variable_is_lowercase
.pdkignore:
  unmanaged: true
.pmtignore:
  required:
    - .gems/
    - .fixtures.yml
    - .gem
    - .git
    - .gitattributes
    - .gitignore
    - .pmtignore
    - .sync.yml
    - develop.sh
    - litmus.sh
    - .gitlab-ci.yml
    - inventory.yaml
    - .byebug_history
    - .pki/
    - app/
    - documentation/
.gitignore:
  required:
    - '.git/'
    - '.*.sw[op]'
    - '.metadata'
    - '.yardwarns'
    - '*.iml'
    - '/.bundle/'
    - '/.idea/'
    - '/coverage/'
    - '/bin/'
    - '/doc/'
    - '/Gemfile.local'
    - '/junit/'
    - '/log/'
    - '/pkg/'
    - '/spec/fixtures/manifests/'
    - '/spec/fixtures/modules/'
    - '/tmp/'
    - '/vendor/'
    - '/convert_report.txt'
    - '/update_report.txt'
    - '.project'
    - '.envrc'
    - '/inventory.yaml'
    - '/.gem'
    - '/.bash_history'
    - '/.local'
    - '/examples/.byebug_history'
    - '/tasks/.byebug_history'
    - '/.puppetlabs'
